# Generated by Django 5.0.3 on 2025-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='UNSET', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_types',
            field=models.CharField(default='card', max_length=20),
        ),
    ]
