# Generated by Django 5.2 on 2025-04-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_size_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cod', 'COD')], default='cod', max_length=20),
        ),
    ]
