version: "3.8"
services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest # Change this line
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
    networks:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250/udp"
    networks:
      - jaeger

networks:
  jaeger: