# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 127.0.0.1:1777
  zpages:
    endpoint: 127.0.0.1:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4319
  opencensus:
    endpoint: 127.0.0.1:55678
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['127.0.0.1:9888']
  jaeger:
    protocols:
      grpc:
        endpoint: 127.0.0.1:14250
      thrift_binary:
        endpoint: 127.0.0.1:6832
      thrift_compact:
        endpoint: 127.0.0.1:6831
      thrift_http:
        endpoint: 127.0.0.1:14270  # changed from 14268 to avoid conflict with Jaeger query server
  zipkin:
    endpoint: 127.0.0.1:9411
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:
      paging:
      processes:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:14320  # Jaeger OTLP gRPC port
    tls:
      insecure: true
  prometheus:
    endpoint: "127.0.0.1:8893"
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"

service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
      address: "127.0.0.1:8891"

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  extensions: [health_check, pprof, zpages]
