auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: C:/Windows/Temp/loki

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: C:/Windows/Temp/loki/index
    cache_location: C:/Windows/Temp/loki/tsdb-cache
  filesystem:
    directory: C:/Windows/Temp/loki/chunks

compactor:
  working_directory: C:/Windows/Temp/loki/compactor

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true