version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otel/config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver 
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3100:3100" # Tempo HTTP endpoint for receiving traces
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml # Path to your Tempo configuration file
      - .//traces:/var/tempo/traces
    command: ["-config.file=/etc/tempo.yaml"] 
    environment:
      - TEMPO_LOG_LEVEL=debug
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set your Grafana admin password
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - tempo
  
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
  
  loki:
    image: grafana/loki:latest
    ports:
      - "3101:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki