groups:
  - name: service-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(http_server_requests_total[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Request rate is over 2 rps for more than 1 minute."
